# Generated by Django 5.1.6 on 2025-03-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='availability',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
